name: CI/CD - Deploy Contracts to Base Goerli

on:
  push:
    branches:
      - master

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install Hardhat dependencies
        working-directory: ./simple-contracts
        run: npm install
      - name: Compile contracts
        working-directory: ./simple-contracts
        run: npx hardhat compile
      - name: Deploy contracts
        working-directory: ./simple-contracts
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          BASE_RPC_URL: ${{ secrets.BASE_RPC_URL }}
        run: npx hardhat run scripts/deploy.js --network base
      - name: Archive artifacts
        uses: actions/upload-artifact@v3
        with:
          name: contract-artifacts
          path: simple-contracts/artifacts/